export { default as Login } from "./Login"
export { default as Password } from "./Password"
export { default as SSO } from "./SSO"
export { default as Verify } from "./Verify"
export { default as Register } from "./Register"
export { default as Recovery } from "./Recovery"
export { default as Sent } from "./Sent"
export { default as Reset } from "./Reset"
