#!/bin/sh
set -e

cat > /usr/share/nginx/html/config.js <<EOF
window.__KEYGEN_CONFIG__ = {
  VITE_KEYGEN_HOST: "${VITE_KEYGEN_HOST:-api.keygen.localhost}",
  VITE_KEYGEN_MODE: "${VITE_KEYGEN_MODE:-singleplayer}",
  VITE_KEYGEN_EDITION: "${VITE_KEYGEN_EDITION:-CE}",
  VITE_KEYGEN_VERSION: "${VITE_KEYGEN_VERSION:-1.8}",
  VITE_KEYGEN_ACCOUNT_ID: "${VITE_KEYGEN_ACCOUNT_ID:-00000000-0000-0000-0000-000000000000}",
  VITE_SENTRY_DSN: "${VITE_SENTRY_DSN:-}",
  VITE_SENTRY_ENVIRONMENT: "${VITE_SENTRY_ENVIRONMENT:-production}"
};
EOF