import { useCallback } from "react"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { z } from "zod"

import {
  FormField,
  FormItem,
  FormControl,
  FormMessage,
} from "@/components/ui/form"

import { useDisableSecondFactor } from "@/queries/second-factors"

import { toast } from "@/lib/toast"

import { type SecondFactor } from "@/types/second-factors"

import * as Forms from "@/components/forms"
import OtpInput from "@/components/otp-input"

const otpSchema = z.object({
  otp: z.string().regex(/^\d{6}$/, "Enter a 6-digit code"),
})

type OtpValues = z.infer<typeof otpSchema>

interface DisableSecondFactorFormProps {
  factor: SecondFactor
  onClose: () => void
}

export default function DisableSecondFactorForm({
  factor,
  onClose,
}: DisableSecondFactorFormProps) {
  const disableSecondFactor = useDisableSecondFactor()

  const form = useForm<OtpValues>({
    resolver: zodResolver(otpSchema),
    mode: "onChange",
    defaultValues: { otp: "" },
  })

  const handleSubmit = useCallback(
    async (values: OtpValues) => {
      await disableSecondFactor.mutateAsync({
        id: factor.id,
        otp: values.otp,
      })
      onClose()
      toast({
        message: "Two-factor authentication disabled",
        variant: "success",
      })
    },
    [disableSecondFactor, factor.id, onClose],
  )

  return (
    <Forms.Provider form={form}>
      <Forms.Container.Page>
        <Forms.Layout.Sheet
          title="Deactivating two-factor authentication"
          onSubmit={handleSubmit}
          errorMessage="Failed to deactivate two-factor authentication"
          isPending={disableSecondFactor.isPending}
          submitLabel="Deactivate"
          onClose={onClose}
          inline
        >
          <Forms.Section.Stacking>
            <p className="text-sm text-content-muted">
              Enter the 6-digit verification code generated by your
              authenticator app.
            </p>
            <FormField
              control={form.control}
              name="otp"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <OtpInput
                      value={field.value}
                      onChange={field.onChange}
                      autoFocus
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </Forms.Section.Stacking>
        </Forms.Layout.Sheet>
      </Forms.Container.Page>
    </Forms.Provider>
  )
}
